version: '3.8'

services:
  postgres_db:
    image: postgres:14-alpine
    container_name: dashboard_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: dashboard_backend
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 5000
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      FRONTEND_URL: http://localhost:3000
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: dashboard_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000/api
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
