# Prometheus Configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'codegen-platform'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets: ['alertmanager:9093']

# Load rules once and periodically evaluate them
# rule_files:
#   - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FastAPI Application
  - job_name: 'fastapi'
    metrics_path: '/api/v1/metrics'
    static_configs:
      - targets: ['app:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'codegen-app'

  # Redis Exporter (if using redis-exporter)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # NATS Monitoring
  - job_name: 'nats'
    metrics_path: '/varz'
    static_configs:
      - targets: ['nats:8222']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nats-server'

  # LiteLLM Metrics (if exposed)
  # - job_name: 'litellm'
  #   static_configs:
  #     - targets: ['litellm:4000']

