# LiteLLM Proxy Configuration

model_list:
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro-latest
      api_key: os.environ/GEMINI_API_KEY
  
  - model_name: gemini-flash
    litellm_params:
      model: gemini/gemini-flash-latest
      api_key: os.environ/GEMINI_API_KEY
  
  - model_name: gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY
  
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY

litellm_settings:
  drop_params: true
  set_verbose: false
  max_parallel_requests: 10
  request_timeout: 300

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  database_url: null
  
# Enable success/failure callbacks
success_callback: []
failure_callback: []

